[package]
name = "anime-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.0-rc.2"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
kitsu = { path = "kitsu", version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.21.2", features = ["full"] }
url = { version = "2", features = ["serde"] }
