[package]
name = "anime-service"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["kitsu", "nyaa", "consume_api"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kitsu = { path = "kitsu" }
nyaa = { path = "nyaa" }

chrono = { version = "0.4", default-features = false, features = ["serde"] }
diesel = { version = "2.0.0", features = ["postgres"] }
dotenvy = "0.15"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = {version = "0.23" }
itertools = "0.10"
once_cell = "1"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.21.2", features = ["full"] }
url = { version = "2", features = ["serde"] }
