[package]
name = "anime-service"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["kitsu", "nyaa"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kitsu = { path = "kitsu" }
nyaa = { path = "nyaa" }

anyhow = "1"
axum = { version = "0.6" }
chrono = { version = "0.4", features = ["serde"] }
envy = "0.4.2"
futures = "0.3.26"
reqwest = { version = "0.11", features = ["native-tls-vendored"] }
itertools = "0.10"
percent-encoding = "2.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.6.2", features = ["postgres", "runtime-tokio-native-tls", "offline", "chrono", "uuid"] }
thiserror = "1"
tower = "0.4"
tower-http = { version = "0.4", features = ["trace", "decompression-full", "compression-full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = "0.1.11"
url = { version = "2", features = ["serde"] }
