[package]
name = "nyaa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
futures = "0.3"
tracing = "0.1"
hyper = { version = "0.14", features = ["client"] }
hyper-rustls = { version = "0.23" }
regex = "1"
rss = "2"
thiserror = "1"
url = "2"